name: dotnet-fsharp-helloworld # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: HelloWorld F# app with snap # 79 char long summary
description: |
  Parse CoinDesk API to show current BTC price.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  dotnet-fsharp-helloworld:
    plugin: dump
    source: ./staging
    build-packages:
      - dotnet-sdk-7.0
    stage-packages:
      - dotnet-runtime-7.0

apps:
  dotnet-fsharp-helloworld:
    command: launch_snap.sh
